import sys

def main():
    if len(sys.argv) != 3:
        print("usage: embed_net.py <input.bin> <output.cpp>")
        sys.exit(1)

    in_path, out_path = sys.argv[1], sys.argv[2]
    with open(in_path, "rb") as f:
        data = f.read()

    with open(out_path, "w") as f:
        f.write("// Auto-generated by tools/embed_net.py\n")
        f.write('extern "C" const unsigned char gEmbeddedNNUEData[] = {\n')
        for i in range(0, len(data), 20):
            f.write(",".join(str(b) for b in data[i:i+20]) + ",\n")
        f.write("};\n")
        f.write('extern "C" const unsigned int gEmbeddedNNUESize = %d;\n' % len(data))

if __name__ == "__main__":
    main()